[tox]
envlist = py310, py311, py312, py313, pylint

[testenv:pylint]
runner = uv-venv-lock-runner
basepython = python
dependency_groups =
    dev
commands = pylint dep_check

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    dev
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pytest --basetemp={envtmpdir}
