name: "Release"

on:
  push:
    branches:
      - master

env:
    python-version: 3.10.6

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
  release:
    timeout-minutes: 30
    name: "Release"
    runs-on: ubuntu-latest
    steps:

      - name: Check the code out
        uses: actions/checkout@v3

      - name: Install Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Initialize .pypirc
        run: |
              echo -e "[pypi]" >> ~/.pypirc
              echo -e "username = lumapps" >> ~/.pypirc
              echo -e "password = $pypi_password" >> ~/.pypirc

      - name: Install CircleCI-specific dependencies
        run: |
              sudo apt update
              sudo apt install -y libenchant-2-2
      - name: Install the project dependencies
        run: make init

      - name: Create package
        run: make dist

      - name: Upload to PyPI
        run: |
              source venv/bin/activate
              twine upload dist/*
